### PR TITLE
Clean up the current build configuration

### PR DESCRIPTION
**Pull request by rafmudaf**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by rafmudaf** [comment]
For our own reference, here's some documentation on the "Build, host, and run" dependencies: https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-host-and-run.

**Review by dzalkind — COMMENTED** [review]
Increment version in meta yaml

**Comment by rafmudaf** [comment]
@conda-forge-admin, please rerender

**Comment by rafmudaf** [comment]
@conda-forge-admin, please rerender

**Comment by rafmudaf** [comment]
@conda-forge-admin, please rerender

**Comment by rafmudaf** [comment]
@conda-forge-admin, please rerender

**Comment by rafmudaf** [comment]
@conda-forge-admin, please rerender

**Comment by rafmudaf** [comment]
@conda-forge-admin, please rerender

**Comment by rafmudaf** [comment]
@conda-forge/core We are really struggling here and could use some guidance.

This project is a Python package and a compiled library. I don't think it's accurate to say it's a C-extension since the compiled library is loaded via ctypes rather than by importing `Python.h`. In fact, the compiled library is written in Fortran with C-bindings.

We are having trouble building this package for Windows with Python 3.10. In that case, there's a dependency on VC 9 and Python 2.7. A question to start is where is this dependency coming from? Here's the error message:

```
Traceback (most recent call last):
  File "C:\Miniforge\lib\site-packages\boa\cli\mambabuild.py", line 141, in mamba_get_install_actions
    solution = solver.solve_for_action(_specs, prefix)
  File "C:\Miniforge\lib\site-packages\boa\core\solver.py", line 230, in solve_for_action
    t = self.solve(specs)
  File "C:\Miniforge\lib\site-packages\boa\core\solver.py", line 220, in solve
    raise RuntimeError("Solver could not find solution." + error_string)
RuntimeError: Solver could not find solution.Mamba failed to solve:
 - scipy
 - m2w64-gcc-libs-core
 - matplotlib-base
 - control
 - pyyaml
 - pandas
 - python >=3.10,<3.11.0a0
 - numpy
 - m2w64-gcc-libs
 - wisdem
 - python_abi 3.10.* *_cp310

with channels:

The reported errors are:
- Encountered problems while solving:
-   - nothing provides vc 9.* needed by python-2.7.12-0
- 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Miniforge\Scripts\conda-mambabuild-script.py", line 9, in <module>
    sys.exit(main())
  File "C:\Miniforge\lib\site-packages\boa\cli\mambabuild.py", line 256, in main
    call_conda_build(action, config)
  File "C:\Miniforge\lib\site-packages\boa\cli\mambabuild.py", line 228, in call_conda_build
    result = api.build(
  File "C:\Miniforge\lib\site-packages\conda_build\api.py", line 180, in build
    return build_tree(
  File "C:\Miniforge\lib\site-packages\conda_build\build.py", line 3097, in build_tree
    packages_from_this = build(metadata, stats,
  File "C:\Miniforge\lib\site-packages\conda_build\build.py", line 2126, in build
    create_build_envs(top_level_pkg, notest)
  File "C:\Miniforge\lib\site-packages\conda_build\build.py", line 2004, in create_build_envs
    raise e
  File "C:\Miniforge\lib\site-packages\conda_build\build.py", line 1983, in create_build_envs
    environ.get_install_actions(m.config.test_prefix,
  File "C:\Miniforge\lib\site-packages\boa\cli\mambabuild.py", line 150, in mamba_get_install_actions
    raise err
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform win-64: {MatchSpec("vc=9"), MatchSpec("python==2.7.12=0")}
```

**Comment by gbarter** [comment]
This can be closed.  Things are simplified and taken care of in the other PR.

**Pull request closed without merging**
